[2023-10-24 14:17:33 +0000] [55607] [INFO] Starting gunicorn 21.2.0
[2023-10-24 14:17:33 +0000] [55607] [INFO] Listening at: http://89.33.44.114:8000 (55607)
[2023-10-24 14:17:33 +0000] [55607] [INFO] Using worker: sync
[2023-10-24 14:17:33 +0000] [55608] [INFO] Booting worker with pid: 55608
[2023-10-24 14:17:33 +0000] [55609] [INFO] Booting worker with pid: 55609
[2023-10-24 14:17:33 +0000] [55608] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/accel/accel/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
[2023-10-24 14:17:33 +0000] [55608] [INFO] Worker exiting (pid: 55608)
[2023-10-24 14:17:34 +0000] [55607] [ERROR] Worker (pid:55608) exited with code 3
[2023-10-24 14:17:34 +0000] [55609] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/accel/vdjango/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/accel/accel/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/root/accel/vdjango/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
[2023-10-24 14:17:34 +0000] [55609] [INFO] Worker exiting (pid: 55609)
[2023-10-24 14:17:34 +0000] [55607] [ERROR] Worker (pid:55609) exited with code 3
[2023-10-24 14:20:44 +0000] [55665] [INFO] Starting gunicorn 21.2.0
[2023-10-24 14:20:44 +0000] [55665] [INFO] Listening at: http://89.33.44.114:8000 (55665)
[2023-10-24 14:20:44 +0000] [55665] [INFO] Using worker: sync
[2023-10-24 14:20:44 +0000] [55666] [INFO] Booting worker with pid: 55666
[2023-10-24 14:20:44 +0000] [55667] [INFO] Booting worker with pid: 55667
[2023-10-24 21:56:40 +0000] [55666] [WARNING] Invalid request from ip=212.70.149.142: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-10-24 23:15:30 +0000] [55667] [WARNING] Invalid request from ip=212.70.149.142: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-10-25 00:33:16 +0000] [55667] [WARNING] Invalid request from ip=212.70.149.142: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-10-25 01:50:20 +0000] [55666] [WARNING] Invalid request from ip=212.70.149.142: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-10-25 03:06:45 +0000] [55666] [WARNING] Invalid request from ip=212.70.149.142: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-10-25 04:22:35 +0000] [55667] [WARNING] Invalid request from ip=212.70.149.142: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
